package iso8583

var Binary87 = IsoSpec{
	&IsoCodec{"DE000", "MESSAGE TYPE INDICATOR", IsoFixed, IsoAscii, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE001", "BIT MAP", IsoFixed, IsoAscii, 16, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE002", "PAN - PRIMARY ACCOUNT NUMBER", IsoFixed, IsoAscii, 19, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE003", "PROCESSING CODE", IsoFixed, IsoAscii, 6, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE004", "AMOUNT, TRANSACTION", IsoFixed, IsoAscii, 12, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE005", "AMOUNT, SETTLEMENT", IsoFixed, IsoAscii, 12, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE006", "AMOUNT, CARDHOLDER BILLING", IsoFixed, IsoAscii, 12, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE007", "TRANSMISSION DATE AND TIME", IsoFixed, IsoAscii, 10, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE008", "AMOUNT, CARDHOLDER BILLING FEE", IsoFixed, IsoAscii, 8, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE009", "CONVERSION RATE, SETTLEMENT", IsoFixed, IsoAscii, 8, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE010", "CONVERSION RATE, CARDHOLDER BILLING", IsoFixed, IsoAscii, 8, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE011", "SYSTEM TRACE AUDIT NUMBER", IsoFixed, IsoAscii, 6, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE012", "TIME, LOCAL TRANSACTION", IsoFixed, IsoAscii, 6, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE013", "DATE, LOCAL TRANSACTION", IsoFixed, IsoAscii, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE014", "DATE, EXPIRATION", IsoFixed, IsoAscii, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE015", "DATE, SETTLEMENT", IsoFixed, IsoAscii, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE016", "DATE, CONVERSION", IsoFixed, IsoAscii, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE017", "DATE, CAPTURE", IsoFixed, IsoAscii, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE018", "MERCHANTS TYPE", IsoFixed, IsoAscii, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE019", "ACQUIRING INSTITUTION COUNTRY CODE", IsoFixed, IsoAscii, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE020", "PAN EXTENDED COUNTRY CODE", IsoFixed, IsoAscii, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE021", "FORWARDING INSTITUTION COUNTRY CODE", IsoFixed, IsoAscii, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE022", "POINT OF SERVICE ENTRY MODE", IsoFixed, IsoAscii, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE023", "CARD SEQUENCE NUMBER", IsoFixed, IsoAscii, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE024", "NETWORK INTERNATIONAL IDENTIFIEER", IsoFixed, IsoAscii, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE025", "POINT OF SERVICE CONDITION CODE", IsoFixed, IsoAscii, 2, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE026", "POINT OF SERVICE PIN CAPTURE CODE", IsoFixed, IsoAscii, 2, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE027", "AUTHORIZATION IDENTIFICATION RESP LEN", IsoFixed, IsoAscii, 1, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE028", "AMOUNT, TRANSACTION FEE", IsoFixed, IsoAscii, 9, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE029", "AMOUNT, SETTLEMENT FEE", IsoFixed, IsoAscii, 9, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE030", "AMOUNT, TRANSACTION PROCESSING FEE", IsoFixed, IsoAscii, 9, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE031", "AMOUNT, SETTLEMENT PROCESSING FEE", IsoFixed, IsoAscii, 9, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE032", "ACQUIRING INSTITUTION IDENT CODE", IsoFixed, IsoAscii, 6, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE033", "FORWARDING INSTITUTION IDENT CODE", IsoFixed, IsoAscii, 11, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE034", "PAN EXTENDED", IsoFixed, IsoAscii, 28, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE035", "TRACK 2 DATA", IsoFixed, IsoAscii, 37, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE036", "TRACK 3 DATA", IsoFixed, IsoAscii, 104, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE037", "RETRIEVAL REFERENCE NUMBER", IsoFixed, IsoAscii, 12, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE038", "AUTHORIZATION IDENTIFICATION RESPONSE", IsoFixed, IsoAscii, 6, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE039", "RESPONSE CODE", IsoFixed, IsoAscii, 2, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE040", "SERVICE RESTRICTION CODE", IsoFixed, IsoAscii, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE041", "CARD ACCEPTOR TERMINAL IDENTIFICACION", IsoFixed, IsoAscii, 8, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE042", "CARD ACCEPTOR IDENTIFICATION CODE", IsoFixed, IsoAscii, 15, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE043", "CARD ACCEPTOR NAME/LOCATION", IsoFixed, IsoAscii, 40, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE044", "ADDITIONAL RESPONSE DATA", IsoFixed, IsoAscii, 25, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE045", "TRACK 1 DATA", IsoFixed, IsoAscii, 76, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE046", "ADDITIONAL DATA - ISO", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE047", "ADDITIONAL DATA - NATIONAL", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE048", "ADDITIONAL DATA - PRIVATE", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE049", "CURRENCY CODE, TRANSACTION", IsoFixed, IsoAscii, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE050", "CURRENCY CODE, SETTLEMENT", IsoFixed, IsoAscii, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE051", "CURRENCY CODE, CARDHOLDER BILLING", IsoFixed, IsoAscii, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE052", "PIN DATA", IsoFixed, IsoAscii, 8, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE053", "SECURITY RELATED CONTROL INFORMATION", IsoFixed, IsoAscii, 16, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE054", "ADDITIONAL AMOUNTS", IsoFixed, IsoAscii, 120, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE055", "RESERVED ISO", IsoFixed, IsoAscii, 255, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE056", "RESERVED ISO", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE057", "RESERVED NATIONAL", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE058", "RESERVED NATIONAL", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE059", "NATIONAL POS GEOGRAPHIC DATA", IsoFixed, IsoAscii, 14, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE060", "RESERVED PRIVATE", IsoFixed, IsoAscii, 6, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE061", "RESERVED PRIVATE", IsoFixed, IsoAscii, 36, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE062", "PAYMENT SERVICE FIELDS", IsoFixed, IsoAscii, 59, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE063", "SMS PRIVATE-USE FIELDS", IsoFixed, IsoAscii, 255, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE064", "MESSAGE AUTHENTICATION CODE FIELD", IsoFixed, IsoAscii, 8, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE065", "BITMAP, EXTENDED", IsoFixed, IsoAscii, 1, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE066", "SETTLEMENT CODE", IsoFixed, IsoAscii, 1, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE067", "EXTENDED PAYMENT CODE", IsoFixed, IsoAscii, 2, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE068", "RECEIVING INSTITUTION COUNTRY CODE", IsoFixed, IsoAscii, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE069", "SETTLEMENT INSTITUTION COUNTRY CODE", IsoFixed, IsoAscii, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE070", "NETWORK MANAGEMENT INFORMATION CODE", IsoFixed, IsoAscii, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE071", "MESSAGE NUMBER", IsoFixed, IsoAscii, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE072", "MESSAGE NUMBER LAST", IsoFixed, IsoAscii, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE073", "DATE ACTION", IsoFixed, IsoAscii, 6, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE074", "CREDITS NUMBER", IsoFixed, IsoAscii, 10, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE075", "CREDITS REVERSAL NUMBER", IsoFixed, IsoAscii, 10, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE076", "DEBITS NUMBER", IsoFixed, IsoAscii, 10, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE077", "DEBITS REVERSAL NUMBER", IsoFixed, IsoAscii, 10, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE078", "TRANSFER NUMBER", IsoFixed, IsoAscii, 10, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE079", "TRANSFER REVERSAL NUMBER", IsoFixed, IsoAscii, 10, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE080", "INQUIRIES NUMBER", IsoFixed, IsoAscii, 10, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE081", "AUTHORIZATION NUMBER", IsoFixed, IsoAscii, 10, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE082", "CREDITS, PROCESSING FEE AMOUNT", IsoFixed, IsoAscii, 12, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE083", "CREDITS, TRANSACTION FEE AMOUNT", IsoFixed, IsoAscii, 12, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE084", "DEBITS, PROCESSING FEE AMOUNT", IsoFixed, IsoAscii, 12, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE085", "DEBITS, TRANSACTION FEE AMOUNT", IsoFixed, IsoAscii, 12, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE086", "CREDITS, AMOUNT", IsoFixed, IsoAscii, 16, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE087", "CREDITS, REVERSAL AMOUNT", IsoFixed, IsoAscii, 16, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE088", "DEBITS, AMOUNT", IsoFixed, IsoAscii, 16, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE089", "DEBITS, REVERSAL AMOUNT", IsoFixed, IsoAscii, 16, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE090", "ORIGINAL DATA ELEMENTS", IsoFixed, IsoAscii, 42, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE091", "FILE UPDATE CODE", IsoFixed, IsoAscii, 1, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE092", "FILE SECURITY CODE", IsoFixed, IsoAscii, 2, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE093", "RESPONSE INDICATOR", IsoFixed, IsoAscii, 5, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE094", "SERVICE INDICATOR", IsoFixed, IsoAscii, 7, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE095", "REPLACEMENT AMOUNTS", IsoFixed, IsoAscii, 42, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE096", "MESSAGE SECURITY CODE", IsoFixed, IsoAscii, 8, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE097", "AMOUNT, NET SETTLEMENT", IsoFixed, IsoAscii, 17, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE098", "PAYEE", IsoFixed, IsoAscii, 25, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE099", "SETTLEMENT INSTITUTION IDENT CODE", IsoFixed, IsoAscii, 11, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE100", "RECEIVING INSTITUTION IDENT CODE", IsoFixed, IsoAscii, 11, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE101", "FILE NAME", IsoFixed, IsoAscii, 17, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE102", "ACCOUNT IDENTIFICATION 1", IsoFixed, IsoAscii, 28, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE103", "ACCOUNT IDENTIFICATION 2", IsoFixed, IsoAscii, 28, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE104", "TRANSACTION DESCRIPTION", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE105", "RESERVED ISO USE", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE106", "RESERVED ISO USE", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE107", "RESERVED ISO USE", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE108", "RESERVED ISO USE", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE109", "RESERVED ISO USE", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE110", "RESERVED ISO USE", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE111", "RESERVED ISO USE", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE112", "RESERVED NATIONAL USE", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE113", "RESERVED NATIONAL USE", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE114", "RESERVED NATIONAL USE", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE115", "ADDITIONAL TRACE DATA 1", IsoFixed, IsoAscii, 24, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE116", "RESERVED NATIONAL USE", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE117", "RESERVED NATIONAL USE", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE118", "INTRA-COUNTRY DATA", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE119", "RESERVED NATIONAL USE", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE120", "RESERVED PRIVATE USE", IsoFixed, IsoAscii, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE121", "ISSUING INSTITUTION IDENT CODE", IsoFixed, IsoAscii, 11, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE122", "REMAINING OPEN-TO-USE", IsoFixed, IsoAscii, 13, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE123", "VERIFICATION AND TOKEN DATA", IsoFixed, IsoAscii, 255, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE124", "FREE-FORM TEXT-JAPAN", IsoFixed, IsoAscii, 99, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE125", "SUPPORTING INFORMATION", IsoFixed, IsoAscii, 255, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE127", "FILE RECORS(S) ACTION/DATA", IsoFixed, IsoAscii, 255, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE128", "MAC 2", IsoFixed, IsoAscii, 8, IsoNumeric, IsoLeftPad},
}