package iso8583

/*
	Should be revised
*/

var Ebcdic87 = IsoSpec{
	&IsoCodec{"DE000", "MTI - MESSAGE TYPE INDICATOR", IsoFixed, IsoEbcdic, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE001", "BITMAP", IsoFixed, IsoBinary, 16, IsoText, IsoNoPad},
	&IsoCodec{"DE002", "PAN - PRIMARY ACCOUNT NUMBER", IsoLLE, IsoEbcdic, 19, IsoNumeric, IsoNoPad},
	&IsoCodec{"DE003", "PROCESSING CODE", IsoFixed, IsoEbcdic, 6, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE004", "AMOUNT, TRANSACTION", IsoFixed, IsoEbcdic, 12, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE005", "AMOUNT, SETTLEMENT", IsoFixed, IsoEbcdic, 12, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE006", "AMOUNT, CARDHOLDER BILLING", IsoFixed, IsoEbcdic, 12, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE007", "TRANSMISSION DATE AND TIME", IsoFixed, IsoEbcdic, 10, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE008", "AMOUNT, CARDHOLDER BILLING FEE", IsoFixed, IsoEbcdic, 8, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE008", "CONVERSION RATE, SETTLEMENT", IsoFixed, IsoEbcdic, 8, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE010", "CONVERSION RATE, CARDHOLDER BILLING", IsoFixed, IsoEbcdic, 8, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE011", "SYSTEM TRACE AUDIT NUMBER", IsoFixed, IsoEbcdic, 6, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE012", "TIME, LOCAL TRANSACTION", IsoFixed, IsoEbcdic, 6, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE013", "DATE, LOCAL TRANSACTION", IsoFixed, IsoEbcdic, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE014", "DATE, EXPIRATION", IsoFixed, IsoEbcdic, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE015", "DATE, SETTLEMENT", IsoFixed, IsoEbcdic, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE016", "DATE, CONVERSION", IsoFixed, IsoEbcdic, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE017", "DATE, CAPTURE", IsoFixed, IsoEbcdic, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE018", "MERCHANTS TYPE", IsoFixed, IsoEbcdic, 4, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE019", "ACQUIRING INSTITUTION COUNTRY CODE", IsoFixed, IsoEbcdic, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE020", "PAN EXTENDED COUNTRY CODE", IsoFixed, IsoEbcdic, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE021", "FORWARDING INSTITUTION COUNTRY CODE", IsoFixed, IsoEbcdic, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE022", "POINT OF SERVICE ENTRY MODE", IsoFixed, IsoEbcdic, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE023", "CARD SEQUENCE NUMBER", IsoFixed, IsoEbcdic, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE024", "NETWORK INTERNATIONAL IDENTIFIEER", IsoFixed, IsoEbcdic, 3, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE025", "POINT OF SERVICE CONDITION CODE", IsoFixed, IsoEbcdic, 2, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE026", "POINT OF SERVICE PIN CAPTURE CODE", IsoFixed, IsoEbcdic, 2, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE027", "AUTHORIZATION IDENTIFICATION RESPONSE LEN", IsoFixed, IsoEbcdic, 1, IsoNumeric, IsoLeftPad},
	&IsoCodec{"DE028", "AMOUNT, TRANSACTION FEE", IsoFixed, IsoEbcdic, 9, IsoText, IsoLeftPad},
	&IsoCodec{"DE029", "AMOUNT, SETTLEMENT FEE", IsoFixed, IsoEbcdic, 9, IsoText, IsoLeftPad},
	&IsoCodec{"DE030", "AMOUNT, TRANSACTION PROCESSING FEE", IsoFixed, IsoEbcdic, 9, IsoText, IsoLeftPad},
	&IsoCodec{"DE031", "AMOUNT, SETTLEMENT PROCESSING FEE", IsoFixed, IsoEbcdic, 9, IsoText, IsoLeftPad},
	&IsoCodec{"DE032", "ACQUIRING INSTITUTION IDENTITY CODE", IsoLLE, IsoEbcdic, 11, IsoNumeric, IsoNoPad},
	&IsoCodec{"DE033", "FORWARDING INSTITUTION IDENTITY CODE", IsoLLE, IsoEbcdic, 11, IsoNumeric, IsoNoPad},
	&IsoCodec{"DE034", "PAN EXTENDED", IsoLLE, IsoEbcdic, 28, IsoText, IsoNoPad},
	&IsoCodec{"DE035", "TRACK 2 DATA", IsoLLE, IsoEbcdic, 37, IsoText, IsoNoPad},
	&IsoCodec{"DE036", "TRACK 3 DATA", IsoLLLE, IsoEbcdic, 104, IsoText, IsoNoPad},
	&IsoCodec{"DE037", "RETRIEVAL REFERENCE NUMBER", IsoFixed, IsoEbcdic, 12, IsoText, IsoLeftPad},
	&IsoCodec{"DE038", "AUTHORIZATION IDENTIFICATION RESPONSE", IsoFixed, IsoEbcdic, 6, IsoText, IsoLeftPad},
	&IsoCodec{"DE039", "RESPONSE CODE", IsoFixed, IsoEbcdic, 2, IsoText, IsoLeftPad},
	&IsoCodec{"DE040", "SERVICE RESTRICTION CODE", IsoFixed, IsoEbcdic, 3, IsoText, IsoLeftPad},
	&IsoCodec{"DE041", "CARD ACCEPTOR TERMINAL IDENTIFICACION", IsoFixed, IsoEbcdic, 8, IsoText, IsoLeftPad},
	&IsoCodec{"DE042", "CARD ACCEPTOR IDENTIFICATION CODE", IsoFixed, IsoEbcdic, 15, IsoText, IsoLeftPad},
	&IsoCodec{"DE043", "CARD ACCEPTOR NAME/LOCATION", IsoFixed, IsoEbcdic, 40, IsoText, IsoLeftPad},
	&IsoCodec{"DE044", "ADITIONAL RESPONSE DATA", IsoLLE, IsoEbcdic, 25, IsoText, IsoNoPad},
	&IsoCodec{"DE045", "TRACK 1 DATA", IsoLLE, IsoEbcdic, 76, IsoText, IsoNoPad},
	&IsoCodec{"DE046", "ADITIONAL DATA - ISO", IsoLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE047", "ADITIONAL DATA - NATIONAL", IsoLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE048", "ADITIONAL DATA - PRIVATE", IsoLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE049", "CURRENCY CODE, TRANSACTION", IsoFixed, IsoEbcdic, 3, IsoText, IsoLeftPad},
	&IsoCodec{"DE050", "CURRENCY CODE, SETTLEMENT", IsoFixed, IsoEbcdic, 3, IsoText, IsoLeftPad},
	&IsoCodec{"DE051", "CURRENCY CODE, CARDHOLDER BILLING", IsoFixed, IsoEbcdic, 3, IsoText, IsoLeftPad},
	&IsoCodec{"DE052", "PIN DATA", IsoFixed, IsoBinary, 8, IsoText, IsoRightPad},
	&IsoCodec{"DE053", "SECURITY RELATED CONTROL INFORMATION", IsoFixed, IsoEbcdic, 16, IsoText, IsoLeftPad},
	&IsoCodec{"DE054", "ADDITIONAL AMOUNTS", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE055", "RESERVED ISO", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE056", "RESERVED ISO", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE057", "RESERVED NATIONAL", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE058", "RESERVED NATIONAL", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE059", "RESERVED NATIONAL", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE060", "RESERVED PRIVATE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE061", "RESERVED PRIVATE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE062", "RESERVED PRIVATE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE063", "RESERVED PRIVATE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE064", "MAC - MESSAGE AUTHENTICATION CODE", IsoFixed, IsoBinary, 8, IsoText, IsoNoPad},
	&IsoCodec{"DE065", "BITMAP, EXTENDED", IsoFixed, IsoBinary, 1, IsoText, IsoNoPad},
	&IsoCodec{"DE066", "SETTLEMENT CODE", IsoFixed, IsoEbcdic, 1, IsoText, IsoLeftPad},
	&IsoCodec{"DE067", "EXTENDED PAYMENT CODE", IsoFixed, IsoEbcdic, 2, IsoText, IsoLeftPad},
	&IsoCodec{"DE068", "RECEIVING INSTITUTION COUNTRY CODE", IsoFixed, IsoEbcdic, 3, IsoText, IsoLeftPad},
	&IsoCodec{"DE069", "SETTLEMENT INSTITUTION COUNTRY CODE", IsoFixed, IsoEbcdic, 3, IsoText, IsoLeftPad},
	&IsoCodec{"DE070", "NETWORK MANAGEMENT INFORMATION CODE", IsoFixed, IsoEbcdic, 3, IsoText, IsoLeftPad},
	&IsoCodec{"DE071", "MESSAGE NUMBER", IsoFixed, IsoEbcdic, 4, IsoText, IsoLeftPad},
	&IsoCodec{"DE072", "MESSAGE NUMBER LAST", IsoFixed, IsoEbcdic, 4, IsoText, IsoLeftPad},
	&IsoCodec{"DE073", "DATE ACTION", IsoFixed, IsoEbcdic, 6, IsoText, IsoLeftPad},
	&IsoCodec{"DE074", "CREDITS NUMBER", IsoFixed, IsoEbcdic, 10, IsoText, IsoLeftPad},
	&IsoCodec{"DE075", "CREDITS REVERSAL NUMBER", IsoFixed, IsoEbcdic, 10, IsoText, IsoLeftPad},
	&IsoCodec{"DE076", "DEBITS NUMBER", IsoFixed, IsoEbcdic, 10, IsoText, IsoLeftPad},
	&IsoCodec{"DE077", "DEBITS REVERSAL NUMBER", IsoFixed, IsoEbcdic, 10, IsoText, IsoLeftPad},
	&IsoCodec{"DE078", "TRANSFER NUMBER", IsoFixed, IsoEbcdic, 10, IsoText, IsoLeftPad},
	&IsoCodec{"DE079", "TRANSFER REVERSAL NUMBER", IsoFixed, IsoEbcdic, 10, IsoText, IsoLeftPad},
	&IsoCodec{"DE080", "INQUIRIES NUMBER", IsoFixed, IsoEbcdic, 10, IsoText, IsoLeftPad},
	&IsoCodec{"DE081", "AUTHORIZATION NUMBER", IsoFixed, IsoEbcdic, 10, IsoText, IsoLeftPad},
	&IsoCodec{"DE082", "CREDITS, PROCESSING FEE AMOUNT", IsoFixed, IsoEbcdic, 12, IsoText, IsoLeftPad},
	&IsoCodec{"DE083", "CREDITS, TRANSACTION FEE AMOUNT", IsoFixed, IsoEbcdic, 12, IsoText, IsoLeftPad},
	&IsoCodec{"DE084", "DEBITS, PROCESSING FEE AMOUNT", IsoFixed, IsoEbcdic, 12, IsoText, IsoLeftPad},
	&IsoCodec{"DE085", "DEBITS, TRANSACTION FEE AMOUNT", IsoFixed, IsoEbcdic, 12, IsoText, IsoLeftPad},
	&IsoCodec{"DE086", "CREDITS, AMOUNT", IsoFixed, IsoEbcdic, 16, IsoText, IsoLeftPad},
	&IsoCodec{"DE087", "CREDITS, REVERSAL AMOUNT", IsoFixed, IsoEbcdic, 16, IsoText, IsoLeftPad},
	&IsoCodec{"DE088", "DEBITS, AMOUNT", IsoFixed, IsoEbcdic, 16, IsoText, IsoLeftPad},
	&IsoCodec{"DE089", "DEBITS, REVERSAL AMOUNT", IsoFixed, IsoEbcdic, 16, IsoText, IsoLeftPad},
	&IsoCodec{"DE090", "ORIGINAL DATA ELEMENTS", IsoFixed, IsoEbcdic, 42, IsoText, IsoLeftPad},
	&IsoCodec{"DE091", "FILE UPDATE CODE", IsoFixed, IsoEbcdic, 1, IsoText, IsoLeftPad},
	&IsoCodec{"DE092", "FILE SECURITY CODE", IsoFixed, IsoEbcdic, 2, IsoText, IsoLeftPad},
	&IsoCodec{"DE093", "RESPONSE INDICATOR", IsoFixed, IsoEbcdic, 6, IsoText, IsoLeftPad},
	&IsoCodec{"DE094", "SERVICE INDICATOR", IsoFixed, IsoEbcdic, 7, IsoText, IsoLeftPad},
	&IsoCodec{"DE095", "REPLACEMENT AMOUNTS", IsoFixed, IsoEbcdic, 42, IsoText, IsoLeftPad},
	&IsoCodec{"DE096", "MESSAGE SECURITY CODE", IsoFixed, IsoBinary, 16, IsoText, IsoNoPad},
	&IsoCodec{"DE097", "AMOUNT, NET SETTLEMENT", IsoFixed, IsoEbcdic, 17, IsoText, IsoLeftPad},
	&IsoCodec{"DE098", "PAYEE", IsoFixed, IsoEbcdic, 25, IsoText, IsoLeftPad},
	&IsoCodec{"DE099", "SETTLEMENT INSTITUTION IDENTIFICATION CODE", IsoLLLE, IsoEbcdic, 11, IsoNumeric, IsoNoPad},
	&IsoCodec{"DE100", "RECEIVING INSTITUTION IDENTIFICATION CODE", IsoLLLE, IsoEbcdic, 11, IsoNumeric, IsoNoPad},
	&IsoCodec{"DE101", "FILE NAME", IsoLLLE, IsoEbcdic, 17, IsoNumeric, IsoNoPad},
	&IsoCodec{"DE102", "ACCOUNT IDENTIFICATION 1", IsoLLE, IsoEbcdic, 28, IsoText, IsoNoPad},
	&IsoCodec{"DE103", "ACCOUNT IDENTIFICATION 2", IsoLLE, IsoEbcdic, 28, IsoText, IsoNoPad},
	&IsoCodec{"DE104", "TRANSACTION DESCRIPTION", IsoLLE, IsoEbcdic, 100, IsoText, IsoNoPad},
	&IsoCodec{"DE105", "RESERVED ISO USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE106", "RESERVED ISO USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE107", "RESERVED ISO USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE108", "RESERVED ISO USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE109", "RESERVED ISO USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE110", "RESERVED ISO USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE111", "RESERVED ISO USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE112", "RESERVED NATIONAL USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE113", "RESERVED NATIONAL USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE114", "RESERVED NATIONAL USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE115", "RESERVED NATIONAL USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE116", "RESERVED NATIONAL USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE117", "RESERVED NATIONAL USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE118", "RESERVED NATIONAL USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE119", "RESERVED NATIONAL USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE120", "RESERVED PRIVATE USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE121", "RESERVED PRIVATE USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE122", "RESERVED PRIVATE USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE123", "RESERVED PRIVATE USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE124", "RESERVED PRIVATE USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE125", "RESERVED PRIVATE USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE126", "RESERVED PRIVATE USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE127", "RESERVED PRIVATE USE", IsoLLLE, IsoEbcdic, 999, IsoText, IsoNoPad},
	&IsoCodec{"DE128", "MAC 2", IsoFixed, IsoBinary, 8, IsoText, IsoNoPad},
}
