package iso8583

type IsoProtocol []*IsoCodec

var IsoProtocolAscii87 = IsoProtocol{
	/* DE000 */ IsoNumeric(Fixed(), ASCII, 4, NoPadding),
	/* DE001 */ IsoText(Fixed(), BINARY, 16, NoPadding),
	/* DE002 */ IsoNumeric(LLVar(ASCII), ASCII, 19, LeftPadding),
	/* DE003 */ IsoNumeric(Fixed(), ASCII, 6, LeftPadding),
	/* DE004 */ IsoNumeric(Fixed(), ASCII, 12, LeftPadding),
	/* DE005 */ IsoNumeric(Fixed(), ASCII, 12, LeftPadding),
	/* DE006 */ IsoNumeric(Fixed(), ASCII, 12, LeftPadding),
	/* DE007 */ IsoNumeric(Fixed(), ASCII, 10, LeftPadding),
	/* DE008 */ IsoNumeric(Fixed(), ASCII, 8, LeftPadding),
	/* DE009 */ IsoNumeric(Fixed(), ASCII, 8, LeftPadding),
	/* DE010 */ IsoNumeric(Fixed(), ASCII, 8, LeftPadding),
	/* DE011 */ IsoNumeric(Fixed(), ASCII, 6, LeftPadding),
	/* DE012 */ IsoNumeric(Fixed(), ASCII, 6, LeftPadding),
	/* DE013 */ IsoNumeric(Fixed(), ASCII, 4, LeftPadding),
	/* DE014 */ IsoNumeric(Fixed(), ASCII, 4, LeftPadding),
	/* DE015 */ IsoNumeric(Fixed(), ASCII, 4, LeftPadding),
	/* DE016 */ IsoNumeric(Fixed(), ASCII, 4, LeftPadding),
	/* DE017 */ IsoNumeric(Fixed(), ASCII, 4, LeftPadding),
	/* DE018 */ IsoNumeric(Fixed(), ASCII, 4, LeftPadding),
	/* DE019 */ IsoNumeric(Fixed(), ASCII, 3, LeftPadding),
	/* DE020 */ IsoNumeric(Fixed(), ASCII, 3, LeftPadding),
	/* DE021 */ IsoNumeric(Fixed(), ASCII, 3, LeftPadding),
	/* DE022 */ IsoNumeric(Fixed(), ASCII, 3, LeftPadding),
	/* DE023 */ IsoNumeric(Fixed(), ASCII, 3, LeftPadding),
	/* DE024 */ IsoNumeric(Fixed(), ASCII, 3, LeftPadding),
	/* DE025 */ IsoNumeric(Fixed(), ASCII, 2, LeftPadding),
	/* DE026 */ IsoNumeric(Fixed(), ASCII, 2, LeftPadding),
	/* DE027 */ IsoNumeric(Fixed(), ASCII, 1, LeftPadding),
	/* DE028 */ IsoText(Fixed(), ASCII, 9, LeftPadding),
	/* DE029 */ IsoText(Fixed(), ASCII, 9, LeftPadding),
	/* DE030 */ IsoText(Fixed(), ASCII, 9, LeftPadding),
	/* DE031 */ IsoText(Fixed(), ASCII, 9, LeftPadding),
	/* DE032 */ IsoNumeric(LLVar(ASCII), ASCII, 11, NoPadding),
	/* DE033 */ IsoNumeric(LLVar(ASCII), ASCII, 11, NoPadding),
	/* DE034 */ IsoText(LLVar(ASCII), ASCII, 28, NoPadding),
	/* DE035 */ IsoText(LLVar(ASCII), ASCII, 37, NoPadding),
	/* DE036 */ IsoText(LLLVar(ASCII), ASCII, 104, NoPadding),
	/* DE037 */ IsoText(Fixed(), ASCII, 12, LeftPadding),
	/* DE038 */ IsoText(Fixed(), ASCII, 6, LeftPadding),
	/* DE039 */ IsoText(Fixed(), ASCII, 2, LeftPadding),
	/* DE040 */ IsoText(Fixed(), ASCII, 3, LeftPadding),
	/* DE041 */ IsoText(Fixed(), ASCII, 8, LeftPadding),
	/* DE042 */ IsoText(Fixed(), ASCII, 15, LeftPadding),
	/* DE043 */ IsoText(Fixed(), ASCII, 40, RightPadding),
	/* DE044 */ IsoText(LLVar(ASCII), ASCII, 25, NoPadding),
	/* DE045 */ IsoText(LLVar(ASCII), ASCII, 76, NoPadding),
	/* DE046 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE047 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE048 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE049 */ IsoText(Fixed(), ASCII, 3, LeftPadding),
	/* DE050 */ IsoText(Fixed(), ASCII, 3, LeftPadding),
	/* DE051 */ IsoText(Fixed(), ASCII, 3, LeftPadding),
	/* DE052 */ IsoText(Fixed(), BINARY, 8, NoPadding),
	/* DE053 */ IsoText(Fixed(), ASCII, 16, LeftPadding),
	/* DE054 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE055 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE056 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE057 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE058 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE059 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE060 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE061 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE062 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE063 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE064 */ IsoText(Fixed(), BINARY, 8, NoPadding),
	/* DE065*/ IsoText(Fixed(), BINARY, 1, NoPadding),
	/* DE066 */ IsoText(Fixed(), ASCII, 1, LeftPadding),
	/* DE067 */ IsoText(Fixed(), ASCII, 2, LeftPadding),
	/* DE068 */ IsoText(Fixed(), ASCII, 3, LeftPadding),
	/* DE069 */ IsoText(Fixed(), ASCII, 3, LeftPadding),
	/* DE070 */ IsoText(Fixed(), ASCII, 3, LeftPadding),
	/* DE071 */ IsoText(Fixed(), ASCII, 4, LeftPadding),
	/* DE072 */ IsoText(Fixed(), ASCII, 4, LeftPadding),
	/* DE073 */ IsoText(Fixed(), ASCII, 6, LeftPadding),
	/* DE074 */ IsoText(Fixed(), ASCII, 10, LeftPadding),
	/* DE075 */ IsoText(Fixed(), ASCII, 10, LeftPadding),
	/* DE076 */ IsoText(Fixed(), ASCII, 10, LeftPadding),
	/* DE077 */ IsoText(Fixed(), ASCII, 10, LeftPadding),
	/* DE078 */ IsoText(Fixed(), ASCII, 10, LeftPadding),
	/* DE079 */ IsoText(Fixed(), ASCII, 10, LeftPadding),
	/* DE080 */ IsoText(Fixed(), ASCII, 10, LeftPadding),
	/* DE081 */ IsoText(Fixed(), ASCII, 10, LeftPadding),
	/* DE082 */ IsoText(Fixed(), ASCII, 12, LeftPadding),
	/* DE083 */ IsoText(Fixed(), ASCII, 12, LeftPadding),
	/* DE084 */ IsoText(Fixed(), ASCII, 12, LeftPadding),
	/* DE085 */ IsoText(Fixed(), ASCII, 12, LeftPadding),
	/* DE086 */ IsoText(Fixed(), ASCII, 16, LeftPadding),
	/* DE087 */ IsoText(Fixed(), ASCII, 16, LeftPadding),
	/* DE088 */ IsoText(Fixed(), ASCII, 16, LeftPadding),
	/* DE089 */ IsoText(Fixed(), ASCII, 16, LeftPadding),
	/* DE090 */ IsoText(Fixed(), ASCII, 42, LeftPadding),
	/* DE091 */ IsoText(Fixed(), ASCII, 1, LeftPadding),
	/* DE092 */ IsoText(Fixed(), ASCII, 2, LeftPadding),
	/* DE093 */ IsoText(Fixed(), ASCII, 6, LeftPadding),
	/* DE094 */ IsoText(Fixed(), ASCII, 7, LeftPadding),
	/* DE095 */ IsoText(Fixed(), ASCII, 42, LeftPadding),
	/* DE096 */ IsoText(Fixed(), BINARY, 16, LeftPadding),
	/* DE097 */ IsoText(Fixed(), ASCII, 17, LeftPadding),
	/* DE098 */ IsoText(Fixed(), ASCII, 25, LeftPadding),
	/* DE099 */ IsoNumeric(LLVar(ASCII), ASCII, 11, NoPadding),
	/* DE100 */ IsoNumeric(LLVar(ASCII), ASCII, 11, NoPadding),
	/* DE101 */ IsoNumeric(LLVar(ASCII), ASCII, 17, NoPadding),
	/* DE102 */ IsoText(LLVar(ASCII), ASCII, 28, NoPadding),
	/* DE103 */ IsoText(LLVar(ASCII), ASCII, 28, NoPadding),
	/* DE104 */ IsoText(LLVar(ASCII), ASCII, 100, NoPadding),
	/* DE105 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE106 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE107 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE108 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE109 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE110 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE111 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE112 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE113 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE114 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE115 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE116 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE117 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE118 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE119 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE120 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE121 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE122 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE123 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE124 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE125 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE126 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE127 */ IsoText(LLLVar(ASCII), ASCII, 999, NoPadding),
	/* DE128 */ IsoText(Fixed(), BINARY, 8, NoPadding),
}

/*
// ASCII1987 ISO 8583:1987 protocol
var ASCII1987 = Protocol{
	ANumericNew("DE000", "MESSAGE TYPE INDICATOR", 4),
	ABinaryNew("DE001", "ASCII encoded bitmap", 16),
	LLANumericNew("DE002", "PRIMARY ACCOUNT NUMBER", 19, false),
	ANumericNew("DE003", "PROCESSING CODE", 6),
	ANumericNew("DE004", "AMOUNT, TRANSACTION", 12),
	ANumericNew("DE005", "AMOUNT, SETTLEMENT", 12),
	ANumericNew("DE006", "AMOUNT, CARDHOLDER BILLING", 12),
	ANumericNew("DE007", "TRANSMISSION DATE AND TIME", 10),
	ANumericNew("DE008", "AMOUNT, CARDHOLDER BILLING FEE", 8),
	ANumericNew("DE009", "CONVERSION RATE, SETTLEMENT", 8),
	ANumericNew("DE010", "CONVERSION RATE, CARDHOLDER BILLING", 8),
	ANumericNew("DE011", "SYSTEM TRACE AUDIT NUMBER", 6),
	ANumericNew("DE012", "TIME, LOCAL TRANSACTION", 6),
	ANumericNew("DE013", "DATE, LOCAL TRANSACTION", 4),
	ANumericNew("DE014", "DATE, EXPIRATION", 4),
	ANumericNew("DE015", "DATE, SETTLEMENT", 4),
	ANumericNew("DE016", "DATE, CONVERSION", 4),
	ANumericNew("DE017", "DATE, CAPTURE", 4),
	ANumericNew("DE018", "MERCHANTS TYPE", 4),
	ANumericNew("DE019", "ACQUIRING INSTITUTION COUNTRY CODE", 3),
	ANumericNew("DE020", "PAN EXTENDED COUNTRY CODE", 3),
	ANumericNew("DE021", "FORWARDING INSTITUTION COUNTRY CODE", 3),
	ANumericNew("DE022", "POINT OF SERVICE ENTRY MODE", 3),
	ANumericNew("DE023", "CARD SEQUENCE NUMBER", 3),
	ANumericNew("DE024", "NETWORK INTERNATIONAL IDENTIFIEER", 3),
	ANumericNew("DE025", "POINT OF SERVICE CONDITION CODE", 2),
	ANumericNew("DE026", "POINT OF SERVICE PIN CAPTURE CODE", 2),
	ANumericNew("DE027", "AUTHORIZATION IDENTIFICATION RESP LEN", 1),
	ACharNew("DE028", "AMOUNT, TRANSACTION FEE", 9),//A_AMOUNT
	ACharNew("DE029", "AMOUNT, SETTLEMENT FEE", 9),//A_AMOUNT
	ACharNew("DE030", "AMOUNT, TRANSACTION PROCESSING FEE", 9),//A_AMOUNT
	ACharNew("DE031", "AMOUNT, SETTLEMENT PROCESSING FEE", 9),//A_AMOUNT
	LLANumericNew("DE032", "ACQUIRING INSTITUTION IDENT CODE", 11, false),
	LLANumericNew("DE033", "FORWARDING INSTITUTION IDENT CODE", 11, false),
	LLACharNew("DE034", "PAN EXTENDED", 28, false),
	LLACharNew("DE035", "TRACK 2 DATA", 37, false),
	LLACharNew("DE036", "TRACK 3 DATA", 104, false),
	ACharNew("DE037", "RETRIEVAL REFERENCE NUMBER", 12),
	ACharNew("DE038", "AUTHORIZATION IDENTIFICATION RESPONSE", 6),
	ACharNew("DE039", "RESPONSE CODE", 2),
	ACharNew("DE040", "SERVICE RESTRICTION CODE", 3),
	ACharNew("DE041", "CARD ACCEPTOR TERMINAL IDENTIFICACION", 8),
	ACharNew("DE042", "CARD ACCEPTOR IDENTIFICATION CODE", 15),
	ACharNew("DE043", "CARD ACCEPTOR NAME/LOCATION", 40),
	LLACharNew("DE044", "ADITIONAL RESPONSE DATA", 25, false),
	LLACharNew("DE045", "TRACK 1 DATA", 76, false),
	LLLACharNew("DE046", "ADITIONAL DATA - ISO", 999, false),
	LLLACharNew("DE047", "ADITIONAL DATA - NATIONAL", 999, false),
	LLLACharNew("DE048", "ADITIONAL DATA - PRIVATE", 999, false),
	ACharNew("DE049", "CURRENCY CODE, TRANSACTION", 3),
	ACharNew("DE050", "CURRENCY CODE, SETTLEMENT", 3),
	ACharNew("DE051", "CURRENCY CODE, CARDHOLDER BILLING", 3),
	ABinaryNew("DE052", "PIN DATA", 8),
	ANumericNew("DE053", "SECURITY RELATED CONTROL INFORMATION", 16),
	LLLACharNew("DE054", "ADDITIONAL AMOUNTS", 120, false),
	LLLACharNew("DE055", "RESERVED ISO", 999, false),
	LLLACharNew("DE056", "RESERVED ISO", 999, false),
	LLLACharNew("DE057", "RESERVED NATIONAL", 999, false),
	LLLACharNew("DE058", "RESERVED NATIONAL", 999, false),
	LLLACharNew("DE059", "RESERVED NATIONAL", 999, false),
	LLLACharNew("DE060", "RESERVED PRIVATE", 999, false),
	LLLACharNew("DE061", "RESERVED PRIVATE", 999, false),
	LLLACharNew("DE062", "RESERVED PRIVATE", 999, false),
	LLLACharNew("DE063", "RESERVED PRIVATE", 999, false),
	ABinaryNew("DE064", "MESSAGE AUTHENTICATION CODE", 8),
	ABinaryNew("DE065", "BITMAP, EXTENDED", 1),
	ANumericNew("DE066", "SETTLEMENT CODE", 1),
	ANumericNew("DE067", "EXTENDED PAYMENT CODE", 2),
	ANumericNew("DE068", "RECEIVING INSTITUTION COUNTRY CODE", 3),
	ANumericNew("DE069", "SETTLEMENT INSTITUTION COUNTRY CODE", 3),
	ANumericNew("DE070", "NETWORK MANAGEMENT INFORMATION CODE", 3),
	ANumericNew("DE071", "MESSAGE NUMBER", 4),
	ANumericNew("DE072", "MESSAGE NUMBER LAST", 4),
	ANumericNew("DE073", "DATE ACTION", 6),
	ANumericNew("DE074", "CREDITS NUMBER", 10),
	ANumericNew("DE075", "CREDITS REVERSAL NUMBER", 10),
	ANumericNew("DE076", "DEBITS NUMBER", 10),
	ANumericNew("DE077", "DEBITS REVERSAL NUMBER", 10),
	ANumericNew("DE078", "TRANSFER NUMBER", 10),
	ANumericNew("DE079", "TRANSFER REVERSAL NUMBER", 10),
	ANumericNew("DE080", "INQUIRIES NUMBER", 10),
	ANumericNew("DE081", "AUTHORIZATION NUMBER", 10),
	ANumericNew("DE082", "CREDITS, PROCESSING FEE AMOUNT", 12),
	ANumericNew("DE083", "CREDITS, TRANSACTION FEE AMOUNT", 12),
	ANumericNew("DE084", "DEBITS, PROCESSING FEE AMOUNT", 12),
	ANumericNew("DE085", "DEBITS, TRANSACTION FEE AMOUNT", 12),
	ANumericNew("DE086", "CREDITS, AMOUNT", 16),
	ANumericNew("DE087", "CREDITS, REVERSAL AMOUNT", 16),
	ANumericNew("DE088", "DEBITS, AMOUNT", 16),
	ANumericNew("DE089", "DEBITS, REVERSAL AMOUNT", 16),
	ANumericNew("DE090", "ORIGINAL DATA ELEMENTS", 42),
	ACharNew("DE091", "FILE UPDATE CODE", 1),
	ACharNew("DE092", "FILE SECURITY CODE", 2),
	ACharNew("DE093", "RESPONSE INDICATOR", 6),
	ACharNew("DE094", "SERVICE INDICATOR", 7),
	ACharNew("DE095", "REPLACEMENT AMOUNTS", 42),
	ABinaryNew("DE096", "MESSAGE SECURITY CODE", 16),
	ACharNew("DE097", "AMOUNT, NET SETTLEMENT", 17),//A_AMOUNT
	ACharNew("DE098", "PAYEE", 25),
	LLANumericNew("DE099", "SETTLEMENT INSTITUTION IDENT CODE", 11, false),
	LLANumericNew("DE0100", "RECEIVING INSTITUTION IDENT CODE", 11, false),
	LLACharNew("DE101", "FILE NAME", 17, false),
	LLACharNew("DE102", "ACCOUNT IDENTIFICATION 1", 28, false),
	LLACharNew("DE103", "ACCOUNT IDENTIFICATION 2", 28, false),
	LLLACharNew("DE104", "TRANSACTION DESCRIPTION", 100, false),
	LLLACharNew("DE105", "RESERVED ISO USE", 999, false),
	LLLACharNew("DE106", "RESERVED ISO USE", 999, false),
	LLLACharNew("DE107", "RESERVED ISO USE", 999, false),
	LLLACharNew("DE108", "RESERVED ISO USE", 999, false),
	LLLACharNew("DE109", "RESERVED ISO USE", 999, false),
	LLLACharNew("DE110", "RESERVED ISO USE", 999, false),
	LLLACharNew("DE111", "RESERVED ISO USE", 999, false),
	LLLACharNew("DE112", "RESERVED NATIONAL USE", 999, false),
	LLLACharNew("DE113", "RESERVED NATIONAL USE", 999, false),
	LLLACharNew("DE114", "RESERVED NATIONAL USE", 999, false),
	LLLACharNew("DE115", "RESERVED NATIONAL USE", 999, false),
	LLLACharNew("DE116", "RESERVED NATIONAL USE", 999, false),
	LLLACharNew("DE117", "RESERVED NATIONAL USE", 999, false),
	LLLACharNew("DE118", "RESERVED NATIONAL USE", 999, false),
	LLLACharNew("DE119", "RESERVED NATIONAL USE", 999, false),
	LLLACharNew("DE120", "RESERVED PRIVATE USE", 999, false),
	LLLACharNew("DE121", "RESERVED PRIVATE USE", 999, false),
	LLLACharNew("DE122", "RESERVED PRIVATE USE", 999, false),
	LLLACharNew("DE123", "RESERVED PRIVATE USE", 999, false),
	LLLACharNew("DE124", "RESERVED PRIVATE USE", 999, false),
	LLLACharNew("DE125", "RESERVED PRIVATE USE", 999, false),
	LLLACharNew("DE126", "RESERVED PRIVATE USE", 999, false),
	LLLACharNew("DE127", "RESERVED PRIVATE USE", 999, false),
	ABinaryNew("DE128", "MAC 2", 8),
}
*/
